export const SET_ADDRESS = "SET_ADDRESS";
export const SET_COORDINATES = "SET_COORDINATES";

export const SET_SEARCHABLE = "SET_SEARCHABLE";
export const SET_UNSEARCHABLE = "SET_UNSEARCHABLE";

export const SET_LOADING = "SET_LOADING";
export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_CURRENT_WEATHER_CONDITIONS = "GET_CURRENT_WEATHER_CONDITIONS";
export const GET_CURRENT_WEATHER_DESCRIPTION =
  "GET_CURRENT_WEATHER_DESCRIPTION";
