export const SET_ADDRESS = "SET_ADDRESS";
export const SET_COORDINATES = "SET_COORDINATES";
export const SET_DISPLAYABLE = "SET_DISPLAYABLE";
export const SET_LOADING = "SET_LOADING";
export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";

export const GET_CURRENT_WEATHER_CONDITIONS = "GET_CURRENT_WEATHER_CONDITIONS";

export const CLEAR_FIELDS = "CLEAR_FIELDS";
